export const categoryConstants = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};
export const productConstants = {
  GET_PRODUCTS_BY_SLUG: " GET_PRODUCTS_BY_SLUG",
  // GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  // GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};
